//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_Spedizioni
    {
        public string ID { get; set; }
        public string IDOriginale1 { get; set; }
        public string IDOriginale2 { get; set; }
        public string IDCliente { get; set; }
        public string IDCasa { get; set; }
        public string IDNave { get; set; }
        public string IDPortoImbarco { get; set; }
        public Nullable<System.DateTime> DataPartenzaImbarco { get; set; }
        public Nullable<System.DateTime> DataInizioImbarco { get; set; }
        public Nullable<System.DateTime> DataFineImbarco { get; set; }
        public string IDPortoSbarco { get; set; }
        public Nullable<System.DateTime> DataArrivoSbarco { get; set; }
        public Nullable<System.DateTime> DataInizioSbarco { get; set; }
        public Nullable<System.DateTime> DataFineSbarco { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> DRichiesta { get; set; }
        public string VRichiesta { get; set; }
        public Nullable<System.DateTime> DDefinizione { get; set; }
        public string VDefinizione { get; set; }
        public Nullable<System.DateTime> DContab { get; set; }
        public string VContab { get; set; }
        public double IRichiesta { get; set; }
        public double IDefinizione { get; set; }
        public double IContab { get; set; }
        public int PDF_P { get; set; }
        public int PDF_A { get; set; }
    }
}
