//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_Porti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AGR_Porti()
        {
            this.AGR_Spedizioni = new HashSet<AGR_Spedizioni>();
            this.AGR_Spedizioni1 = new HashSet<AGR_Spedizioni>();
        }
    
        public string ID { get; set; }
        public string Descr { get; set; }
        public string IDCitta { get; set; }
        public string IDValuta { get; set; }
        public string Email { get; set; }
        public string ID_Perito { get; set; }
        public string EmailGrimaldi { get; set; }
        public string EmailGrimaldiNuovo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGR_Spedizioni> AGR_Spedizioni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AGR_Spedizioni> AGR_Spedizioni1 { get; set; }
    }
}
