//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_SpedizioniWEB_Decoded_vw
    {
        public string ID { get; set; }
        public string Descr { get; set; }
        public Nullable<System.DateTime> DataInizioImbarco { get; set; }
        public string IDCliente { get; set; }
        public string IDCasa { get; set; }
        public string IDNave { get; set; }
        public string Nave { get; set; }
        public string IDPortoImbarco { get; set; }
        public string POL { get; set; }
        public Nullable<System.DateTime> DataPartenzaImbarco { get; set; }
        public Nullable<System.DateTime> DataFineImbarco { get; set; }
        public string IDPortoSbarco { get; set; }
        public string POD { get; set; }
        public Nullable<System.DateTime> DataArrivoSbarco { get; set; }
        public Nullable<System.DateTime> DataInizioSbarco { get; set; }
        public Nullable<System.DateTime> DataFineSbarco { get; set; }
        public string IDOriginale1 { get; set; }
        public string IDOriginale2 { get; set; }
        public string Casa { get; set; }
    }
}
