//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_Parti
    {
        public string ID { get; set; }
        public string IDOriginale { get; set; }
        public string IDCasa { get; set; }
        public string DescrITA { get; set; }
        public string DescrENG { get; set; }
        public string IDClasse { get; set; }
        public string IDCliente { get; set; }
        public string DescrESP { get; set; }
    }
}
