//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_ConteggioPerizieInseriteWEB
    {
        public int ID { get; set; }
        public string Spedizione { get; set; }
        public string Viaggio { get; set; }
        public Nullable<int> Cnt { get; set; }
        public string IDTP { get; set; }
        public Nullable<System.DateTime> DataInsert { get; set; }
    }
}
