//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_PERIZIE_TEMP_MVC_LOG
    {
        public int ID { get; set; }
        public string IDPerizia { get; set; }
        public string Telaio { get; set; }
        public Nullable<System.DateTime> InsertDate { get; set; }
        public string IDPerito { get; set; }
        public Nullable<int> IDOperatore { get; set; }
        public string MachineName { get; set; }
        public string TipoOperazione { get; set; }
    }
}
