//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_FilesTxt
    {
        public int ID { get; set; }
        public string NomeFile { get; set; }
        public string Contenuto { get; set; }
        public string IDGestione { get; set; }
        public bool IsVisible { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string POL { get; set; }
        public string POD { get; set; }
        public string IDSpedizione { get; set; }
        public string IDOriginale { get; set; }
    }
}
