//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_DatiRotabiliInUSo_vw
    {
        public string Telaio { get; set; }
        public string ID_TrasportatoreGrimaldi { get; set; }
        public string ID_TipoRotabile { get; set; }
        public string ID { get; set; }
        public System.DateTime DataPerizia { get; set; }
    }
}
