//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AGR_PERIZIE_DETT_TEMP_MVC_SDU_vw
    {
        public int ID { get; set; }
        public string IDPerizia { get; set; }
        public string IDParte { get; set; }
        public string IDDanno { get; set; }
        public Nullable<short> Qta { get; set; }
        public string Note { get; set; }
        public string IDGravita { get; set; }
        public string IDResponsabilita { get; set; }
        public string IDAttribuzione { get; set; }
        public Nullable<int> Flags { get; set; }
        public string In_Out { get; set; }
        public string PosLetter { get; set; }
        public Nullable<int> PosNumber { get; set; }
        public string PosSide { get; set; }
        public string Parte { get; set; }
        public string Danno { get; set; }
        public string Gravita { get; set; }
    }
}
