//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BKP_AGR_Perizie_TEMP_MVC_ELIMINATE_vw
    {
        public string ID { get; set; }
        public string IDPerito { get; set; }
        public string IDTipoPerizia { get; set; }
        public Nullable<System.DateTime> DataPerizia { get; set; }
        public string Telaio { get; set; }
        public Nullable<int> IDModello { get; set; }
    }
}
