//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periti
    {
        public string ID { get; set; }
        public Nullable<System.DateTime> LastUpdt { get; set; }
        public string Descr { get; set; }
        public string IDModem { get; set; }
        public string F_T_X { get; set; }
        public Nullable<int> TelexFax { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string Telefono3 { get; set; }
        public string FAX { get; set; }
        public string EmailAddress { get; set; }
        public string SistemaOperativo { get; set; }
        public string EmailAccount { get; set; }
        public string EmailPassword { get; set; }
        public string SMTPServer { get; set; }
        public string POPServer { get; set; }
        public int LastFileNumber { get; set; }
        public short DaysHistorical { get; set; }
        public string Win3SVersion { get; set; }
        public string DBVersion { get; set; }
        public string Indirizzo { get; set; }
        public string Localita { get; set; }
        public string CAP { get; set; }
        public Nullable<short> MaxDelay { get; set; }
        public string TechManual { get; set; }
        public string IDCitta { get; set; }
        public string ContactName0 { get; set; }
        public string ContactMobile0 { get; set; }
        public string ContactName1 { get; set; }
        public string ContactMobile1 { get; set; }
        public string NotePerito { get; set; }
        public Nullable<System.DateTime> StartValidity { get; set; }
        public Nullable<System.DateTime> EndValidity { get; set; }
        public string Memo { get; set; }
        public string CittaServite { get; set; }
        public string EmailInvad { get; set; }
    }
}
