//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_ListaPerizieFlat_DEF_C_ALL_90_vw
    {
        public int ID { get; set; }
        public string IDPerizia { get; set; }
        public string IDSpedizione { get; set; }
        public string Viaggio { get; set; }
        public string POL { get; set; }
        public string POD { get; set; }
        public Nullable<System.DateTime> DataPartenzaImbarco { get; set; }
        public Nullable<System.DateTime> DataArrivoSbarco { get; set; }
        public string Nave { get; set; }
        public string Cliente { get; set; }
        public string Telaio { get; set; }
        public string Modello { get; set; }
        public Nullable<System.DateTime> DataPerizia { get; set; }
        public string IDTipoPerizia { get; set; }
        public string Trasportatore { get; set; }
        public Nullable<short> Qta { get; set; }
        public string Note { get; set; }
        public string Parte { get; set; }
        public string Danno { get; set; }
        public string Gravita { get; set; }
        public Nullable<int> Cnt { get; set; }
        public string STATUS { get; set; }
        public Nullable<short> NumFoto { get; set; }
    }
}
