//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_AUTO_ListaSpedizioni_CMN_vw
    {
        public string ID { get; set; }
        public string IDOriginale1 { get; set; }
        public Nullable<int> NumPerizie { get; set; }
        public Nullable<int> Good { get; set; }
        public Nullable<int> Damaged { get; set; }
        public bool IsClosed { get; set; }
        public string IDPerito { get; set; }
        public Nullable<System.DateTime> DataPartenzaImbarco { get; set; }
        public Nullable<System.DateTime> DataArrivoSbarco { get; set; }
        public Nullable<int> NumPDF { get; set; }
        public int Prog { get; set; }
        public string IDTipoPerizia { get; set; }
    }
}
