//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_AUTO_FOTO_X_EMAIL
    {
        public int ID { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
    }
}
