//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_Auto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEB_Auto_ListaPerizieXSpedizione_vw
    {
        public string ID { get; set; }
        public string Telaio { get; set; }
        public string Modello { get; set; }
        public string IDSpedizione { get; set; }
        public string IDTipoPerizia { get; set; }
        public Nullable<System.DateTime> DataPerizia { get; set; }
        public Nullable<short> NumFoto { get; set; }
        public string POL { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string POD { get; set; }
        public Nullable<System.DateTime> ETD { get; set; }
        public string Status { get; set; }
        public string IDPerito { get; set; }
        public string IDMeteo { get; set; }
        public string ID_TrasportatoreGrimaldi { get; set; }
        public string ID_TipoRotabile { get; set; }
        public string FlgNuovoUsato { get; set; }
        public Nullable<int> IDModello { get; set; }
        public string Note { get; set; }
    }
}
